### ISSUE TITLE
Pinch and rotation can not be recognized

### ISSUE THREAD

**Issue by my-fish** [longseespace/react-native-hammerjs#2]
In the example ReactNativeHammerJSExample, the gestures pinch and rotation can not be recognized, both in iOS simulator and device.

**Comment by WillCoco** [comment]
Pinch do not work on android ，rn 0.38

**Comment by longseespace** [comment]
The issue is fixed for iOS in [`v2.0.11`](https://www.npmjs.com/package/react-native-hammerjs). I'm closing this issue.
Note: still doesn't work on Android due to this bug: [https://github.com/facebook/react-native/issues/7221](https://github.com/facebook/react-native/issues/7221). Please head to [https://github.com/longseespace/react-native-hammerjs/issues/4](https://github.com/longseespace/react-native-hammerjs/issues/4) for Android-related issues
